config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  resources :articles do
    resources :comments, only: :create
  end

  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.includes(:user).order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def edit
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to root_path
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def search
    @articles = Article.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end


  private
  def article_params
    params.require(:article).permit(:title,:description,:image,category_ids: []).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/articles/#{comment.article.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, article_id: params[:article_id])
  end
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/articles/_article.html.erb
<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <img src="<%= article.image %>" alt="Placeholder image">
    </figure>
    <p id="author"><%= link_to article.title, article_path(article.id), method: :get %></p>
    <% if article.categories.any? %>
    <p id="category">Categories: <%= render article.categories %></p>
    <% end %>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= link_to article.user.nickname, user_path(article.user.id) %></p>
      </div>
    </div>

    <div class="content">

      <p>
        <%= article.description %>
      </p>

      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <span class="icon is-small"><i class="fas fa-reply"></i></span>
          </a>
          <a class="level-item" href="http://twitter.com/share?url=<%=request.url%>&text=<%=article.description%>&hashtags=wiki_log" target="_blank">
            <span class="icon is-small">
              <i class="fas fa-retweet"></i>
            </span>
          </a>
          <a class="level-item">
            <span class="icon is-small"><i class="fas fa-heart"></i></span>
          </a>
        </div>
      </nav>
      <time datetime="time"><%= time_ago_in_words(article.updated_at) %> ago</time>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div>
  <%= render partial: "shared/errors", locals: { obj: @article } %>
</div>
<label class="label">Image</label>
<div class="control">
  <%= form.text_field :image, placeholder: "Image Url", class: "input"%>
</div>

<label class="label">Title</label>
<div class="control">
  <%= form.text_area :title, placeholder: "title" , rows: "1", class: "input" %>
</div>

<label class="label">Description</label>
<div class="control">
  <%= form.text_area :description, placeholder: "description" , rows: "10", class: "textarea" %>
</div>

<label class="label">Category</label>
<div class="control">
  <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
  <% cb.label(class: "checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
  <% end %>
</div>

<div class="control">
  <%= form.submit "SEND", class: "button is-info" %>
</div>

app/views/articles/edit.html.erb
<div class="field">
  <div class="form-bg">
    <%= form_with(model: @article, local: true) do |form| %>
    <p class="title is-1 is-spaced">
      Edit
    </p>
    <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |form| %>
  <div class="field is-grouped">
    <div class="control is-expanded">
      <%= form.text_field :keyword, placeholder: "Search", class: "input" %>
    </div>
    <div class="control">
      <%= form.submit "Search", class: "button is-info" %>
    </div>
  </div>
<% end %>

<div class="">
  <% @articles.each do |article| %>
    <%= render partial: "article", locals: { article: article } %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="field">
  <div class="form-bg">
    <%= form_with(model: @article, local: true) do |form| %>
    <p class="title is-1 is-spaced">
      Post
    </p>
    <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<p class="title is-1 is-spaced has-text-centered">
  <%= @article.title %></p>

<div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <img src="<%= @article.image %>" alt="Placeholder image">
    </figure>
    <p id="author"><%= link_to @article.title, article_path(@article.id), method: :get %></p>
    <% if @article.categories.any? %>
    <p id="category">Categories: <%= render @article.categories %></p>
    <% end %>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= link_to @article.user.nickname, user_path(@article.user.id) %></p>
      </div>
    </div>

    <div class="content">

      <p>
        <%= @article.description %>
      </p>

      <% if user_signed_in? && current_user.id == @article.user_id %>
      <%= link_to 'Edit', edit_article_path(@article.id), method: :get %>
      <%= link_to 'Delete', article_path(@article.id), method: :delete %>
      </p>
      <% end %>

      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <span class="icon is-small"><i class="fas fa-reply"></i></span>
          </a>
          <a class="level-item"
            href="http://twitter.com/share?url=<%=request.url%>&text=<%=@article.description%>&hashtags=wiki_log"
            target="_blank">
            <span class="icon is-small">
              <i class="fas fa-retweet"></i>
            </span>
          </a>
          <a class="level-item">
            <span class="icon is-small"><i class="fas fa-heart"></i></span>
          </a>
        </div>
      </nav>
      <time datetime="time"><%= time_ago_in_words(@article.updated_at) %> ago</time>
    </div>
  </div>
</div>

<p class="title is-1 is-spaced has-text-centered">
  Comment
</p>

<article class="media">
  <div class="media-content">
    <% if current_user %>
      <%= form_with(model: [@article, @comment], local: true) do |form| %>
      <div class="field">
        <div class="control">
          <%= form.text_area :text, placeholder: "comment", rows: "2", class: "textarea"%>
        </div>
        <div class="control">
          <%= form.submit "SEND" ,class: "button is-info "%>
        </div>
      </div>
    <% end %>
    <% else %>
    <div>
      <strong>
        <p class="has-text-centered	">
          <%= link_to "if you want comment Login Here", new_user_session_path, class: 'post' %></p>
      </strong>
    </div>
    <% end %>

    <div class="">
      <% if @comments %>
      <% @comments.each do |comment| %>
      <p>
        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
        <%= comment.text %>
      </p>
      <% end %>
      <% end %>
    </div>

  </div>
</article>

app/views/categories/_category.html.erb
  <li><%= link_to category.name, category_path(category) %></li>

app/views/categories/index.html.erb

<div class="field">
  <p class="title is-1 is-spaced">Listing all categories</p>
  <% @categories.each do |category| %>
    <%= render partial: "category", locals: { category: category } %>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="field">
  <%= form_with(model: @category, local: true) do |form| %>
    <h3>
      Create new category
    </h3>
    <%= render partial: "form", locals: { form: form } %>
  <% end %>
</div>

<div class="">
  <%= link_to "return to articles listing", articles_path %>
</div>

app/views/categories/show.html.erb
<div class="field">
  <p class="title is-1 is-spaced">Category: <%= @category.name %></p>
</div>

<% if user_signed_in? && current_user.admin? %>
<li>
  <%= link_to "Edit category name", edit_category_path(@category) %>
</li>
<li>
  <%= link_to 'Delete Category', category_path(@category.id), method: :delete %>
</li>
<% end %>
<% @category_articles.each do |article| %>
<%= render partial: "articles/article", locals: { article: article } %>
<% end %>

app/views/layouts/_messages.html.erb


<% flash.each do |name, msg| %>
  <div class="notification is-light is-<%="#{name}" %>">
    <button class="delete"></button>
      <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= image_pack_tag 'icon.png' %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Categories
        </a>
        <div class="navbar-dropdown">
          <a class="navbar-item"><%= link_to "All Category", categories_path %></a>
          <hr class="navbar-divider">
          <% Category.all.each do |category| %>
          <a class="navbar-item">
            <%= link_to category.name, category_path(category) %>
          </a>
          <% end %>
          <hr class="navbar-divider">
          <% if user_signed_in? && current_user.admin? %>
            <a class="navbar-item"><%= link_to "New Category(admin)", new_category_path %></a>
          <% end %>
        </div>
      </div>

      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href='/users/<%= current_user.id %>'>
            <%= current_user.nickname %>'s Profile
          </a>
          <a class="navbar-item" href='/users/edit' data-method="get">
            Edit Profile
          </a>

          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons ">

          <% if user_signed_in? %>
          <a class="button is-light" href='/articles/new'>
            New Article
          </a>

          <a class="button is-light" href='/users/sign_out' data-method="delete">
            logout
          </a>

          <% else %>
          <a class="button is-light" href='/users/sign_in'>
            Login
          </a>

          <a class="button is-light" href='/users/sign_up'>
            Signup
          </a>
          <% end %>

        </div>

      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>WikiLog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="field">
    <div class="field">
      <%= render 'layouts/navigation' %>
    </div>
    <% if flash%>
    <div class="field">
      <%= render 'layouts/messages' %>
    </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>

</html>

app/views/toppage/about.html.erb
<h1>About</h1>

<%= link_to'Home', root_path %>

app/views/toppage/top.html.erb
<div class="">
  <h1>Wiki_log</h1>
  <%= link_to "Sign up now", signup_path, class: "" %>
</div>

app/views/users/show.html.erb
<div class="">
  <p><%= @nickname %>'s Post</p>
  <% @articles.each do |article| %>
  <%= render partial: "articles/article", locals: { article: article } %>
  <% end %>
  <%= link_to "Edit your profile", edit_user_registration_path(current_user) %>
</div>